name: Build / Test / Push

on:
  push:
    branches:
      - '**'
  workflow_dispatch:

env:
  BUILD_SUFFIX: -build-${{ github.run_id }}_${{ github.run_attempt }}
  DOCKER_METADATA_SET_OUTPUT_ENV: 'true'

jobs:
  build:
    runs-on: ${{ matrix.runner }}
    outputs:
      image-arm64: ${{ steps.gen-output.outputs.image-arm64 }}
      image-x64: ${{ steps.gen-output.outputs.image-x64 }}
    strategy:
      fail-fast: false
      matrix:
        runner:
          - ubuntu-24.04
          - ubuntu-24.04-arm
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - id: build-meta
        name: Docker meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository }}
          tags: type=sha,suffix=${{ env.BUILD_SUFFIX }}

      # Build cache is shared among all builds of the same architecture
      - id: cache-meta
        name: Docker meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository }}
          tags: type=raw,value=buildcache-${{ runner.arch }}

      - id: get-registry
        name: Get the sanitized registry name
        run: |
          echo "registry=$(echo '${{ steps.build-meta.outputs.tags }}' | cut -f1 -d:)" | tee -a "$GITHUB_OUTPUT"

      - id: build
        name: Build/push the arch-specific image
        uses: docker/build-push-action@v6
        with:
          cache-from: type=registry,ref=${{ steps.cache-meta.outputs.tags }}
          cache-to: type=registry,ref=${{ steps.cache-meta.outputs.tags }},mode=max
          labels: ${{ steps.build-meta.outputs.labels }}
          provenance: mode=max
          sbom: true
          tags: ${{ steps.get-registry.outputs.registry }}
          outputs: type=image,push-by-digest=true,push=true

      - id: gen-output
        name: Write arch-specific image digest to outputs
        run: |
          echo "image-${RUNNER_ARCH,,}=${{ steps.get-registry.outputs.registry }}@${{ steps.build.outputs.digest }}" | tee -a "$GITHUB_OUTPUT"

  merge:
    runs-on: ubuntu-24.04
    needs: build
    env:
      DOCKER_APP_IMAGE_ARM64: ${{ needs.build.outputs.image-arm64 }}
      DOCKER_APP_IMAGE_X64: ${{ needs.build.outputs.image-x64 }}
    outputs:
      image: ${{ steps.meta.outputs.tags }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - id: meta
        name: Generate tag for the app image
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository }}
          tags: type=sha,suffix=${{ env.BUILD_SUFFIX }}

      - name: Push the multi-platform app image
        run: |
          docker buildx imagetools create \
            --tag "$DOCKER_METADATA_OUTPUT_TAGS" \
            "$DOCKER_APP_IMAGE_ARM64" "$DOCKER_APP_IMAGE_X64"


  test-startup:
    runs-on: ubuntu-24.04
    needs: merge
    container:
      image: ${{ needs.merge.outputs.image }}
      # without this we run into permissions issues on Github Actions
      options: --user root
    env:
      COMPOSE_FILE: docker-compose.yml:docker-compose.ci.yml
      DOCKER_APP_IMAGE: ${{ needs.merge.outputs.image }}
    outputs:
      compose-logs: ${{ steps.artifacts.outputs.compose-logs }}
      compose-config: ${{ steps.artifacts.outputs.compose-config }}
      docker-events: ${{ steps.artifacts.outputs.docker-events }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Compose
        uses: docker/setup-compose-action@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup and start Airflow containers
        env:
          FERNET_KEY: ${{ secrets.FERNET_KEY }}
          # below is just to avoid triggering GHA's secrets detection
          _AIRFLOW_WWW_USER_PASSWORD: "::add-mask::airflow"
          AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: ::add-mask::postgresql+psycopg2://airflow:airflow@postgres/airflow
          AIRFLOW__CELERY__RESULT_BACKEND: ::add-mask::db+postgresql://airflow:airflow@postgres/airflow
        run: |
          docker compose up -d postgres redis --wait
          docker compose run airflow-init
          docker compose up -d --wait

      - name: Copy out artifacts
        if: ${{ always() }}
        id: artifacts
        env:
          FERNET_KEY: ${{ secrets.FERNET_KEY }}
          # below is just to avoid triggering GHA's secrets detection
          _AIRFLOW_WWW_USER_PASSWORD: ::add-mask::airflow
          AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: ::add-mask::postgresql+psycopg2://airflow:airflow@postgres/airflow
          AIRFLOW__CELERY__RESULT_BACKEND: ::add-mask::db+postgresql://airflow:airflow@postgres/airflow
        run: |
          EOF=$(dd if=/dev/urandom bs=15 count=1 status=none | base64)
          echo "compose-logs<<$EOF" | tee -a "$GITHUB_OUTPUT"
          docker compose logs | tee -a "$GITHUB_OUTPUT"
          echo "$EOF" | tee -a "$GITHUB_OUTPUT"
          echo "compose-config<<$EOF" | tee -a "$GITHUB_OUTPUT"
          docker compose config | tee -a "$GITHUB_OUTPUT"
          echo "$EOF" | tee -a "$GITHUB_OUTPUT"
          echo "docker-events<<$EOF" | tee -a "$GITHUB_OUTPUT"
          docker events --format '{{ json . }}' --since $TEST_START --until `date +%s` | tee -a "$GITHUB_OUTPUT"
          echo "$EOF" | tee -a "$GITHUB_OUTPUT"

  test-dag-imports:
    runs-on: ubuntu-24.04
    outputs:
      xmlrunner: ${{ steps.artifacts.outputs.xmlrunner }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version-file: ".python-version"
          pip-install: apache-airflow==3.1.6 -r requirements.txt

      - name: Run Dag import test
        run: |
          python test/run_tests.py

      - name: Copy out artifacts
        id: artifacts
        if: ${{ always() }}
        run: |
          EOF=$(dd if=/dev/urandom bs=15 count=1 status=none | base64)
          echo "xmlrunner<<$EOF" | tee -a "$GITHUB_OUTPUT"
          cat artifacts/unittest/airflow_test.xml | tee -a "$GITHUB_OUTPUT"
          echo "$EOF" | tee -a "$GITHUB_OUTPUT"

  upload-artifacts:
    runs-on: ubuntu-24.04
    needs:
      - test-startup
      - test-dag-imports
    steps:
      - name: Set ARTIFACTS_DIR
        run: echo "ARTIFACTS_DIR=${RUNNER_TEMP}/artifacts" >> $GITHUB_ENV

      - name: Create the artifacts directory
        run: mkdir -p "$ARTIFACTS_DIR/unittests"
      - name: Create artifact outputs
        env:
          COMPOSE_CONFIG: ${{ needs.test-startup.outputs.compose-config }}
          COMPOSE_LOGS: ${{ needs.test-startup.outputs.compose-logs }}
          DOCKER_EVENTS: ${{ needs.test-startup.outputs.docker-events }}
          XMLRUNNER: ${{ needs.test-dag-imports.outputs.xmlrunner }}
        run: |
          echo "$COMPOSE_CONFIG" | tee "$ARTIFACTS_DIR/docker-compose.merged.yml"
          echo "$COMPOSE_LOGS" | tee "$ARTIFACTS_DIR/docker-services.log"
          echo "$DOCKER_EVENTS" | tee "$ARTIFACTS_DIR/docker-events.json"
          echo "$XMLRUNNER" | tee "$ARTIFACTS_DIR/unittests/airflow_test.xml"
      - name: Upload test report
        if: ${{ always() }}
        uses: actions/upload-artifact@v4
        with:
          name: mokelumne Test Report (${{ github.sha }}-${{ github.run_id }}-${{ github.run_attempt }})
          path: ${{ env.ARTIFACTS_DIR }}
          if-no-files-found: error

  push:
    runs-on: ubuntu-24.04
    needs:
      - merge
      - upload-artifacts
    env:
      DOCKER_APP_IMAGE: ${{ needs.merge.outputs.image }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Produce permanent image tags
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository }}
          tags: |
            type=sha
            type=ref,event=branch
            type=raw,value=latest,enable={{is_default_branch}}

      - name: Retag and push the image
        run: |
          docker pull "$DOCKER_APP_IMAGE"
          echo "$DOCKER_METADATA_OUTPUT_TAGS" | tr ' ' '\n' | xargs -n1 docker tag "$DOCKER_APP_IMAGE"
          docker push --all-tags "$(echo "$DOCKER_APP_IMAGE" | cut -f1 -d:)"
